# Generated by Django 4.1 on 2022-08-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='uniqueid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
