export const GET_HISTORY_LIST_REQUEST = "GET_HISTORY_LIST_REQUEST";
export const GET_HISTORY_LIST_SUCCESS = "GET_HISTORY_LIST_SUCCESS";
export const GET_HISTORY_LIST_FAILED = "GET_HISTORY_LIST_REQUEST";

export const ADD_HISTORY_REQUEST = "ADD_HISTORY_REQUEST";
export const ADD_HISTORY_SUCCESS = "ADD_HISTORY_SUCCESS";
export const ADD_HISTORY_FAILED = "ADD_HISTORY_FAILED";

export const DELETE_HISTORY_REQUEST = "DELETE_HISTORY_REQUEST";
export const DELETE_HISTORY_SUCCESS = "DELETE_HISTORY_SUCCESS";
export const DELETE_HISTORY_FAILED = "DELETE_HISTORY_FAILED";
