export const GET_PRODUCT_LIST_REQUEST = "GET_PRODUCT_LIST_REQUEST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAILED = "GET_PRODUCT_LIST_FAILED";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const UPDATE_PRODUCT_PATCH_REQUEST = "UPDATE_PRODUCT_PATCH_REQUEST";
export const UPDATE_PRODUCT_PATCH_SUCCESS = "UPDATE_PRODUCT_PATCH_SUCCESS";
export const UPDATE_PRODUCT_PATCH_FAILED = "UPDATE_PRODUCT_PATCH_FAILED";

export const UPDATE_PRODUCT_PUT_REQUEST = "UPDATE_PRODUCT_PUT_REQUEST";
export const UPDATE_PRODUCT_PUT_SUCCESS = "UPDATE_PRODUCT_PUT_SUCCESS";
export const UPDATE_PRODUCT_PUT_FAILED = "UPDATE_PRODUCT_PUT_FAILED";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const GET_PRODUCT_IMAGES_REQUEST = "GET_PRODUCT_IMAGES_REQUEST";
export const GET_PRODUCT_IMAGES_SUCCESS = "GET_PRODUCT_IMAGES_SUCCESS";
export const GET_PRODUCT_IMAGES_FAILED = "GET_PRODUCT_IMAGES_FAILED";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAILED = "GET_PRODUCT_DETAILS_FAILED";

export const GET_PRODUCT_FILES_REQUEST = "GET_PRODUCT_FILES_REQUEST";
export const GET_PRODUCT_FILES_SUCCESS = "GET_PRODUCT_FILES_SUCCESS";
export const GET_PRODUCT_FILES_FAILED = "GET_PRODUCT_FILES_FAILED";

export const DELETE_PRODUCT_IMAGE_REQUEST = "DELETE_PRODUCT_IMAGE_REQUEST";
export const DELETE_PRODUCT_IMAGE_SUCCESS = "DELETE_PRODUCT_IMAGE_SUCCESS";
export const DELETE_PRODUCT_IMAGE_FAILED = "DELETE_PRODUCT_IMAGE_REQUEST";

export const DELETE_PRODUCT_FILE_REQUEST = "DELETE_PRODUCT_FILE_REQUEST";
export const DELETE_PRODUCT_FILE_SUCCESS = "DELETE_PRODUCT_FILE_SUCCESS";
export const DELETE_PRODUCT_FILE_FAILED = "DELETE_PRODUCT_FILE_REQUEST";

export const ADD_PRODUCT_IMAGE_REQUEST = "ADD_PRODUCT_IMAGE_REQUEST";
export const ADD_PRODUCT_IMAGE_SUCCESS = "ADD_PRODUCT_IMAGE_SUCCESS";
export const ADD_PRODUCT_IMAGE_FAILED = "ADD_PRODUCT_IMAGE_REQUEST";

export const ADD_PRODUCT_FILE_REQUEST = "ADD_PRODUCT_FILE_REQUEST";
export const ADD_PRODUCT_FILE_SUCCESS = "ADD_PRODUCT_FILE_SUCCESS";
export const ADD_PRODUCT_FILE_FAILED = "ADD_PRODUCT_FILE_REQUEST";
